name: CI/CD Pipeline for AKS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: k8steamcontainerregistry.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image to ACR
      run: |
        docker build -t k8steamcontainerregistry.azurecr.io/myapp:$GITHUB_SHA .
        docker push k8steamcontainerregistry.azurecr.io/myapp:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'latest'

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/myapp-deployment myapp-container=k8steamcontainerregistry.azurecr.io/myapp:$GITHUB_SHA
        kubectl rollout status deployment/myapp-deployment